### ISSUE TITLE
[advanced] TypeError: argument of type 'module' is not iterable

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#14]
We have to fix this:
<pre>Traceback (most recent call last):
  File "/usr/share/thus/thus/installation/advanced.py", line 782, in on_partition_list_edit_activate
    self.update_view()
  File "/usr/share/thus/thus/installation/advanced.py", line 786, in update_view
    self.fill_partition_list()
  File "/usr/share/thus/thus/installation/advanced.py", line 646, in fill_partition_list
    self.check_mount_points()
  File "/usr/share/thus/thus/installation/advanced.py", line 1686, in check_mount_points
    if mnt == "/boot" and "f2fs" not in fs and "btrfs" not in fs and self.lv_partitions:
TypeError: argument of type 'module' is not iterable
</pre>

**Comment by philmmanjaro** [comment]
Fixed with 48e275e505b49b4aa5a7512b288f7121e9a7b811
