### ISSUE TITLE
[advanced] UnboundLocalError: local variable 'efiboot' referenced before assignment

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#16]
<pre>Traceback (most recent call last):
  File "/usr/share/thus/thus/main_window.py", line 361, in on_forward_button_clicked
    stored = self.current_page.store_values()
  File "/usr/share/thus/thus/installation/advanced.py", line 1960, in store_values
    self.create_staged_partitions()
  File "/usr/share/thus/thus/installation/advanced.py", line 2046, in create_staged_partitions
    if (mnt == '/boot' and efiboot):
UnboundLocalError: local variable 'efiboot' referenced before assignment
</pre>

**Comment by philmmanjaro** [comment]
Fixed with ad7ed2686dc1ad112f17b3bf2b9af5c2b8865675
