### ISSUE TITLE
[advanced] NameError: name 'bootloader_type' is not defined

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#17]
<pre>Traceback (most recent call last):
  File "/usr/share/thus/thus/main_window.py", line 361, in on_forward_button_clicked
    stored = self.current_page.store_values()
  File "/usr/share/thus/thus/installation/advanced.py", line 1963, in store_values
    self.start_installation()
  File "/usr/share/thus/thus/installation/advanced.py", line 2191, in start_installation
    self.settings.set('bootloader_type', bootloader_type)
NameError: name 'bootloader_type' is not defined
</pre>

**Comment by philmmanjaro** [comment]
Fixed with 7d2016ad9ece5a065036c53f7525b9c4deaaf8ca

**Comment by philmmanjaro** [comment]
Fixed with 7d2016ad9ece5a065036c53f7525b9c4deaaf8ca
