### ISSUE TITLE
[automatic] partitioning currently broken

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#20]
**Thus 0.8.12.016-4**

We have followed issue:
<pre>[2015-04-14 15:20:23] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-04-14 15:20:23] [auto_partition] DEBUG: Total disk size: 8192MiB
[2015-04-14 15:20:23] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-04-14 15:20:23] [auto_partition] DEBUG: Swap partition size: 820MiB
[2015-04-14 15:20:23] [auto_partition] DEBUG: Root partition size: 7115MiB
2048+0 records in
2048+0 records out
[2015-04-14 15:20:25] [auto_partition] DEBUG: Boot: /dev/sda1
[2015-04-14 15:20:25] [auto_partition] DEBUG: Swap: /dev/sda3
[2015-04-14 15:20:25] [auto_partition] DEBUG: Root: /dev/sda2
[2015-04-14 15:20:25] [auto_partition] DEBUG: Device /dev/sda2 will have a ext4 filesystem
[2015-04-14 15:20:25] [auto_partition] DEBUG: Device /dev/sda1 will have a ext2 filesystem
[2015-04-14 15:20:25] [auto_partition] DEBUG: Device /dev/sda3 will have a swap filesystem
[2015-04-14 15:20:25] [auto_partition] DEBUG: Will format device /dev/sda2 as ext4
/dev/sda2 contains a ext4 file system labelled 'ManjaroRoot'
	last mounted on Tue Apr 14 15:09:59 2015
[2015-04-14 15:20:30] [auto_partition] DEBUG: Device details: /dev/sda2 UUID=cebf8ac1-7f2f-4e7e-b115-98af68d9fd06 LABEL=ManjaroRoot
[2015-04-14 15:20:30] [auto_partition] DEBUG: Will format device /dev/sda3 as swap
mkswap: cannot open /dev/sda3: No such device or address
[2015-04-14 15:20:30] [auto_partition] WARNING: Can't activate swap in /dev/sda3
[2015-04-14 15:20:30] [auto_partition] WARNING: Command ['mkswap', '-L', 'ManjaroSwap', '/dev/sda3'] failed
[2015-04-14 15:20:30] [auto_partition] WARNING: Output: None
[2015-04-14 15:20:30] [process] ERROR: Error running command ['blkid', '/dev/sda3']
[2015-04-14 15:20:30] [process] ERROR: Output: b''
[2015-04-14 15:20:30] [process] ERROR: ['Traceback (most recent call last):\n', '  File "/usr/share/thus/thus/installation/process.py", line 262, in run\n    self.run_installation()\n', '  File "/usr/share/thus/thus/misc/misc.py", line 175, in helper\n    return func(*args, **kwargs)\n', '  File "/usr/share/thus/thus/installation/process.py", line 333, in run_installation\n    auto.run()\n', '  File "/usr/share/thus/thus/installation/auto_partition.py", line 868, in run\n    self.mkfs(devices[\'swap\'], fs_devices[devices[\'swap\']], mount_points[\'swap\'], labels[\'swap\'])\n', '  File "/usr/share/thus/thus/installation/auto_partition.py", line 436, in mkfs\n    fs_uuid = get_info(device)[\'UUID\']\n', '  File "/usr/share/thus/thus/installation/auto_partition.py", line 60, in get_info\n    ret = subprocess.check_output(cmd).decode().strip()\n', '  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output\n    raise CalledProcessError(retcode, process.args, output=output)\n', "subprocess.CalledProcessError: Command '['blkid', '/dev/sda3']' returned non-zero exit status 2\n"]</pre>

Checking with fstab we have this:
<pre>Device     Boot    Start      End  Sectors  Size Id Type
/dev/sda1  *        2048   524287   522240  255M 83 Linux
/dev/sda2         524288 15095807 14571520    7G 83 Linux
/dev/sda3       15095808 16775167  1679360  820M  f W95 Ext'd (LBA)
/dev/sda5       15097856 16775167  1677312  819M 82 Linux swap / Solaris
</pre>

This means, if we wanna change how we create partitions we have also change the engine. Currently it is a regression which totally breaks installation using MBR.

**Comment by Kirek** [comment]
After which commit is this tested?

**Comment by Kirek** [comment]
Fixed with https://github.com/manjaro/thus/commit/23e58eabb64e8184559cee807c7c2c252e7be466
