### ISSUE TITLE
[auto-partitioning] LVM currently broken

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/thus#24]
[Latest LVM changes](https://github.com/manjaro/thus/commit/e58fb38b23ccd9db19b8574def5b64809b34d744) seems to break LVM support in auto-partitioning. We have to check it again:
<pre>[2015-05-25 22:51:16] [ask] INFO: Manjaro will be installed using LVM volumes
[2015-05-25 22:51:16] [ask] INFO: Manjaro will be installed using a separate /home volume.
[2015-05-25 22:51:16] [automatic] DEBUG: ATA VBOX HARDDISK [8 GB] (/dev/sda)
[2015-05-25 22:51:16] [automatic] DEBUG: ATA VBOX HARDDISK [0 GB] (/dev/sdb)
[2015-05-25 22:51:19] [automatic] INFO: Automatic install on /dev/sda
[2015-05-25 22:51:19] [automatic] INFO: Thus will install Manjaro on device /dev/sda
[2015-05-25 22:51:19] [automatic] INFO: Thus will install the bootloader 'grub2' in device '/dev/sda'
[2015-05-25 22:51:19] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-05-25 22:51:19] [auto_partition] DEBUG: Total disk size: 7104MiB
[2015-05-25 22:51:19] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-25 22:51:19] [auto_partition] DEBUG: LVM physical volume size: 6847MiB
[2015-05-25 22:51:19] [auto_partition] DEBUG: Swap partition size: 711MiB
[2015-05-25 22:51:19] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-25 22:51:19] [auto_partition] DEBUG: Home partition size: -364MiB
2048+0 records in
2048+0 records out
[2015-05-25 22:51:21] [auto_partition] DEBUG: Boot: /dev/sda1
[2015-05-25 22:51:21] [auto_partition] DEBUG: Swap: /dev/ManjaroVG/ManjaroSwap
[2015-05-25 22:51:21] [auto_partition] DEBUG: Root: /dev/ManjaroVG/ManjaroRoot
[2015-05-25 22:51:21] [auto_partition] DEBUG: Home: /dev/ManjaroVG/ManjaroHome
[2015-05-25 22:51:21] [auto_partition] DEBUG: Thus will setup LVM on device /dev/sda2
  Wiping ext4 signature on /dev/sda2.
  Physical volume "/dev/sda2" successfully created
  Volume group "ManjaroVG" successfully created
[2015-05-25 22:51:21] [auto_partition] DEBUG: Real ManjaroVG volume group size: 6844 MiB
[2015-05-25 22:51:21] [auto_partition] DEBUG: Reajusting logical volume sizes
[2015-05-25 22:51:22] [auto_partition] DEBUG: Total disk size: 7101MiB
[2015-05-25 22:51:22] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-25 22:51:22] [auto_partition] DEBUG: LVM physical volume size: 6844MiB
[2015-05-25 22:51:22] [auto_partition] DEBUG: Swap partition size: 711MiB
[2015-05-25 22:51:22] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-25 22:51:22] [auto_partition] DEBUG: Home partition size: -367MiB
  Logical volume "ManjaroRoot" created.
  Rounding up size to full physical extent 712.00 MiB
  Volume group "ManjaroVG" has insufficient free space (86 extents): 178 required.
[2015-05-25 22:51:22] [auto_partition] ERROR: Error creating LVM logical volume
[2015-05-25 22:51:22] [auto_partition] ERROR: Command ['lvcreate', '--name', 'ManjaroSwap', '--yes', '--size', '711', 'ManjaroVG'] failed
[2015-05-25 22:51:22] [auto_partition] ERROR: Output: None
Process InstallationProcess-1:
Traceback (most recent call last):
  File "/usr/share/thus/thus/installation/auto_partition.py", line 840, in run
    subprocess.check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lvcreate', '--name', 'ManjaroSwap', '--yes', '--size', '711', 'ManjaroVG']' returned non-zero exit status 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/share/thus/thus/installation/process.py", line 269, in run
    self.run_installation()
  File "/usr/share/thus/thus/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)
  File "/usr/share/thus/thus/installation/process.py", line 325, in run_installation
    auto.run()
  File "/usr/share/thus/thus/installation/auto_partition.py", line 849, in run
    raise InstallError(txt)
misc.misc.InstallError: 'Error creating LVM logical volume'</pre>

**Comment by philmmanjaro** [comment]
Thus **0.8.12.300 (0.8.13-rc1)** seems to be still fine, so this regression was introduced with the new LVM changes ...
<pre>[2015-05-25 23:07:10] [ask] INFO: Manjaro will be installed using LVM volumes
[2015-05-25 23:07:10] [ask] INFO: Manjaro will be installed using a separate /home volume.
[2015-05-25 23:07:10] [automatic] DEBUG: ATA VBOX HARDDISK [8 GB] (/dev/sda)
[2015-05-25 23:07:10] [automatic] DEBUG: ATA VBOX HARDDISK [0 GB] (/dev/sdb)
[2015-05-25 23:07:13] [automatic] INFO: Automatic install on /dev/sda
[2015-05-25 23:07:13] [automatic] INFO: Thus will install Manjaro on device /dev/sda
[2015-05-25 23:07:13] [automatic] INFO: Thus will install the bootloader 'grub2' in device '/dev/sda'
[2015-05-25 23:07:13] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-05-25 23:07:13] [auto_partition] DEBUG: Total disk size: 8192MiB
[2015-05-25 23:07:13] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-25 23:07:13] [auto_partition] DEBUG: LVM physical volume size: 7935MiB
[2015-05-25 23:07:13] [auto_partition] DEBUG: Swap partition size: 820MiB
[2015-05-25 23:07:13] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-25 23:07:13] [auto_partition] DEBUG: Home partition size: 615MiB
/dev/ManjaroVG/ManjaroHome: 2 bytes were erased at offset 0x00000438 (ext4): 53 ef
  Logical volume "ManjaroHome" successfully removed
/dev/ManjaroVG/ManjaroRoot: 2 bytes were erased at offset 0x00000438 (ext4): 53 ef
  Logical volume "ManjaroRoot" successfully removed
/dev/ManjaroVG/ManjaroSwap: 10 bytes were erased at offset 0x00000ff6 (swap): 53 57 41 50 53 50 41 43 45 32
  Logical volume "ManjaroSwap" successfully removed
  Volume group "ManjaroVG" successfully removed
  Labels on physical volume "/dev/sda2" successfully wiped
2048+0 records in
2048+0 records out
[2015-05-25 23:07:16] [auto_partition] DEBUG: Boot: /dev/sda1
[2015-05-25 23:07:16] [auto_partition] DEBUG: Swap: /dev/ManjaroVG/ManjaroSwap
[2015-05-25 23:07:16] [auto_partition] DEBUG: Root: /dev/ManjaroVG/ManjaroRoot
[2015-05-25 23:07:16] [auto_partition] DEBUG: Home: /dev/ManjaroVG/ManjaroHome
[2015-05-25 23:07:16] [auto_partition] DEBUG: Thus will setup LVM on device /dev/sda2
  Physical volume "/dev/sda2" successfully created
  Volume group "ManjaroVG" successfully created
[2015-05-25 23:07:16] [auto_partition] DEBUG: Real ManjaroVG volume group size: 7932 MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: Reajusting logical volume sizes
[2015-05-25 23:07:16] [auto_partition] DEBUG: Total disk size: 8189MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: LVM physical volume size: 7932MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: Swap partition size: 819MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-25 23:07:16] [auto_partition] DEBUG: Home partition size: 613MiB
  Logical volume "ManjaroRoot" created.
  Rounding up size to full physical extent 820.00 MiB
  Logical volume "ManjaroSwap" created.
  Logical volume "ManjaroHome" created.
[2015-05-25 23:07:17] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroRoot will have a ext4 filesystem
[2015-05-25 23:07:17] [auto_partition] DEBUG: Device /dev/sda1 will have a ext2 filesystem
[2015-05-25 23:07:17] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroHome will have a ext4 filesystem
[2015-05-25 23:07:17] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroSwap will have a swap filesystem
[2015-05-25 23:07:17] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroRoot as ext4
[2015-05-25 23:07:21] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroRoot UUID=8845820d-03dc-47be-b403-fc132543ae7a LABEL=ManjaroRoot
[2015-05-25 23:07:21] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroSwap as swap
Setting up swapspace version 1, size = 820 MiB (859828224 bytes)
LABEL=ManjaroSwap, UUID=249f24b9-fc69-4ae8-ac36-e2970b223959
[2015-05-25 23:07:21] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroSwap UUID=249f24b9-fc69-4ae8-ac36-e2970b223959 LABEL=ManjaroSwap
[2015-05-25 23:07:21] [auto_partition] DEBUG: Will format device /dev/sda1 as ext2
/dev/sda1 contains a ext2 file system labelled 'ManjaroBoot'
	last mounted on Mon May 25 22:59:30 2015
[2015-05-25 23:07:22] [auto_partition] DEBUG: Device details: /dev/sda1 UUID=9cf1b54c-ddb6-4cb2-856b-386f5a3795db LABEL=ManjaroBoot
[2015-05-25 23:07:22] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroHome as ext4
[2015-05-25 23:07:23] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroHome UUID=6f39bfac-537f-4e4f-95ff-f262a04ab1ea LABEL=ManjaroHome
[2015-05-25 23:07:23] [auto_partition] DEBUG: /dev/sda1 will be mounted as /boot
[2015-05-25 23:07:23] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroRoot will be mounted as /
[2015-05-25 23:07:23] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroSwap will be mounted as swap
[2015-05-25 23:07:23] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroHome will be mounted as /home
[2015-05-25 23:07:23] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroRoot will have a ext4 filesystem
[2015-05-25 23:07:23] [auto_partition] DEBUG: Device /dev/sda1 will have a ext2 filesystem
[2015-05-25 23:07:23] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroHome will have a ext4 filesystem
[2015-05-25 23:07:23] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroSwap will have a swap filesystem
</pre>

**Comment by philmmanjaro** [comment]
Using **msdos** table will result in:
<pre>[2015-05-25 23:46:04] [ask] INFO: Manjaro will be installed using LVM volumes
[2015-05-25 23:46:04] [ask] INFO: Manjaro will be installed using a separate /home volume.
[2015-05-25 23:46:05] [automatic] DEBUG: ATA VBOX HARDDISK [8 GB] (/dev/sda)
[2015-05-25 23:46:05] [automatic] DEBUG: ATA VBOX HARDDISK [0 GB] (/dev/sdb)
[2015-05-25 23:46:12] [automatic] INFO: Automatic install on /dev/sda
[2015-05-25 23:46:12] [automatic] INFO: Thus will install Manjaro on device /dev/sda
[2015-05-25 23:46:12] [automatic] INFO: Thus will install the bootloader 'grub2' in device '/dev/sda'
[2015-05-25 23:46:12] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-05-25 23:46:12] [auto_partition] DEBUG: Total disk size: 7104MiB
[2015-05-25 23:46:12] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-25 23:46:12] [auto_partition] DEBUG: LVM physical volume size: 6847MiB
[2015-05-25 23:46:12] [auto_partition] DEBUG: Swap partition size: 711MiB
[2015-05-25 23:46:12] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-25 23:46:12] [auto_partition] DEBUG: Home partition size: -364MiB
2048+0 records in
2048+0 records out
[2015-05-25 23:46:14] [auto_partition] DEBUG: Boot: /dev/sda1
[2015-05-25 23:46:14] [auto_partition] DEBUG: Swap: /dev/ManjaroVG/ManjaroSwap
[2015-05-25 23:46:14] [auto_partition] DEBUG: Root: /dev/ManjaroVG/ManjaroRoot
[2015-05-25 23:46:14] [auto_partition] DEBUG: Home: /dev/ManjaroVG/ManjaroHome
[2015-05-25 23:46:14] [auto_partition] DEBUG: Thus will setup LVM on device /dev/sda2
  Can't initialize physical volume "/dev/sda2" of volume group "ManjaroVG" without -ff
[2015-05-25 23:46:14] [auto_partition] ERROR: Error creating LVM physical volume
[2015-05-25 23:46:14] [auto_partition] ERROR: Command ['pvcreate', '-f', '-y', '/dev/sda2'] failed
[2015-05-25 23:46:14] [auto_partition] ERROR: Output: None
Process InstallationProcess-1:
Traceback (most recent call last):
  File "/usr/share/thus/thus/installation/auto_partition.py", line 799, in run
    subprocess.check_call(["pvcreate", "-f", "-y", devices['lvm']])
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pvcreate', '-f', '-y', '/dev/sda2']' returned non-zero exit status 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/share/thus/thus/installation/process.py", line 269, in run
    self.run_installation()
  File "/usr/share/thus/thus/misc/misc.py", line 175, in helper
    return func(*args, **kwargs)
  File "/usr/share/thus/thus/installation/process.py", line 325, in run_installation
    auto.run()
  File "/usr/share/thus/thus/installation/auto_partition.py", line 805, in run
    raise InstallError(txt)
misc.misc.InstallError: 'Error creating LVM physical volume'</pre>

<pre>Model: ATA VBOX HARDDISK (scsi)
Disk /dev/sda: 8590MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  268MB   267MB   primary  ext2         boot
 2      268MB   7448MB  7180MB  primary               lvm
</pre>

**Comment by philmmanjaro** [comment]
fixed with b1427d693514a4cb5ded0c2bff5a56519a2ba9ca

<pre>[2015-05-26 00:43:10] [ask] INFO: Manjaro will be installed using LVM volumes
[2015-05-26 00:43:10] [ask] INFO: Manjaro will be installed using a separate /home volume.
[2015-05-26 00:43:10] [automatic] DEBUG: ATA VBOX HARDDISK [8 GB] (/dev/sda)
[2015-05-26 00:43:10] [automatic] DEBUG: ATA VBOX HARDDISK [0 GB] (/dev/sdb)
[2015-05-26 00:43:19] [automatic] INFO: Automatic install on /dev/sda
[2015-05-26 00:43:19] [automatic] INFO: Thus will install Manjaro on device /dev/sda
[2015-05-26 00:43:19] [automatic] INFO: Thus will install the bootloader 'grub2' in device '/dev/sda'
[2015-05-26 00:43:19] [process] DEBUG: Creating partitions and their filesystems in /dev/sda
[2015-05-26 00:43:19] [auto_partition] DEBUG: Total disk size: 8191MiB
[2015-05-26 00:43:19] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-26 00:43:19] [auto_partition] DEBUG: LVM physical volume size: 7934MiB
[2015-05-26 00:43:19] [auto_partition] DEBUG: Swap partition size: 820MiB
[2015-05-26 00:43:19] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-26 00:43:19] [auto_partition] DEBUG: Home partition size: 614MiB
  Logical volume "ManjaroRoot" successfully removed
  Volume group "ManjaroVG" successfully removed
  Labels on physical volume "/dev/sda2" successfully wiped
2048+0 records in
2048+0 records out
[2015-05-26 00:43:22] [auto_partition] DEBUG: Boot: /dev/sda1
[2015-05-26 00:43:22] [auto_partition] DEBUG: Swap: /dev/ManjaroVG/ManjaroSwap
[2015-05-26 00:43:22] [auto_partition] DEBUG: Root: /dev/ManjaroVG/ManjaroRoot
[2015-05-26 00:43:22] [auto_partition] DEBUG: Home: /dev/ManjaroVG/ManjaroHome
[2015-05-26 00:43:22] [auto_partition] DEBUG: Thus will setup LVM on device /dev/sda2
  Physical volume "/dev/sda2" successfully created
  Volume group "ManjaroVG" successfully created
[2015-05-26 00:43:22] [auto_partition] DEBUG: Real ManjaroVG volume group size: 7932 MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: Reajusting logical volume sizes
[2015-05-26 00:43:22] [auto_partition] DEBUG: Total disk size: 8189MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: Boot partition size: 256MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: LVM physical volume size: 7932MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: Swap partition size: 819MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: Root partition size: 6500MiB
[2015-05-26 00:43:22] [auto_partition] DEBUG: Home partition size: 613MiB
  Logical volume "ManjaroRoot" created.
  Rounding up size to full physical extent 820.00 MiB
  Logical volume "ManjaroSwap" created.
  Logical volume "ManjaroHome" created.
[2015-05-26 00:43:22] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroRoot will have a ext4 filesystem
[2015-05-26 00:43:22] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroSwap will have a swap filesystem
[2015-05-26 00:43:22] [auto_partition] DEBUG: Device /dev/sda1 will have a ext2 filesystem
[2015-05-26 00:43:22] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroHome will have a ext4 filesystem
[2015-05-26 00:43:22] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroRoot as ext4
[2015-05-26 00:43:26] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroRoot UUID=f79dd6ea-c72e-4c11-b235-a811d47d3e73 LABEL=ManjaroRoot
[2015-05-26 00:43:26] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroSwap as swap
Setting up swapspace version 1, size = 820 MiB (859828224 bytes)
LABEL=ManjaroSwap, UUID=331968df-c776-4cb6-8d98-d17df146d372
[2015-05-26 00:43:27] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroSwap UUID=331968df-c776-4cb6-8d98-d17df146d372 LABEL=ManjaroSwap
[2015-05-26 00:43:27] [auto_partition] DEBUG: Will format device /dev/sda1 as ext2
/dev/sda1 contains a ext2 file system labelled 'ManjaroBoot'
	last mounted on /install/boot on Mon May 25 23:14:13 2015
[2015-05-26 00:43:28] [auto_partition] DEBUG: Device details: /dev/sda1 UUID=b4fc5a13-372a-4516-b8a1-dc1dbc139e9a LABEL=ManjaroBoot
[2015-05-26 00:43:28] [auto_partition] DEBUG: Will format device /dev/ManjaroVG/ManjaroHome as ext4
[2015-05-26 00:43:29] [auto_partition] DEBUG: Device details: /dev/ManjaroVG/ManjaroHome UUID=ffed2896-1337-4d0d-b13a-dc1927d0830d LABEL=ManjaroHome
[2015-05-26 00:43:29] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroSwap will be mounted as swap
[2015-05-26 00:43:29] [auto_partition] DEBUG: /dev/sda1 will be mounted as /boot
[2015-05-26 00:43:29] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroHome will be mounted as /home
[2015-05-26 00:43:29] [auto_partition] DEBUG: /dev/ManjaroVG/ManjaroRoot will be mounted as /
[2015-05-26 00:43:29] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroRoot will have a ext4 filesystem
[2015-05-26 00:43:29] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroSwap will have a swap filesystem
[2015-05-26 00:43:29] [auto_partition] DEBUG: Device /dev/sda1 will have a ext2 filesystem
[2015-05-26 00:43:29] [auto_partition] DEBUG: Device /dev/ManjaroVG/ManjaroHome will have a ext4 filesystem
</pre>
